//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int nid_product { get; set; }
        public string CategoryID { get; set; }
        public string Code { get; set; }
        public string Group { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public string PriceUSD { get; set; }
        public string Price_ind { get; set; }
        public string CategoryName { get; set; }
        public string Bonus { get; set; }
        public string Vendor { get; set; }
        public string Model { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string RecommendedPrice { get; set; }
        public string DDP { get; set; }
        public string Warranty { get; set; }
        public string Stock { get; set; }
        public string Note { get; set; }
        public string DayDelivery { get; set; }
        public string ProductID { get; set; }
        public string UKTVED { get; set; }
        public string GroupID { get; set; }
        public string ClassID { get; set; }
        public string ClassName { get; set; }
        public string Available { get; set; }
    }
}
