//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategory
    {
        public int nid_category { get; set; }
        public string cname_category { get; set; }
        public int subcategory1 { get; set; }
    }
}
